GET http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies?genre=Action

###
POST http://localhost:3000/movies
Content-Type: application/json

{
    "id": "dcdd0fad-a94c-4810-8acc-5f108d3b18c3",
    "title": "The Shawshank Redemption",
    "year": 1994,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
      "Drama"
    ],
    "rate": 9.3
  }

###
PATCH http://localhost:3000/movies/04986507-b3ed-442c-8ae7-4c5df804f896
Content-Type: application/json

{
    "year": 1995
}

### Delete

DELETE http://localhost:3000/movies/04986507-b3ed-442c-8ae7-4c5df804f896
